/**
 * Initialize
 */
export const SET_ACTIVE_CANDIDATE = "SET_ACTIVE_CANDIDATE";
export const INITIALIZE_CANDIDATE_HUB = "INITIALIZE_CANDIDATE_HUB";
export const REQUEST_INITIALIZATION = "REQUEST_INITIALIZATION";
export const INITIALIZATION_SUCCESS = "INITIALIZATION_SUCCESS";
export const INITIALIZATION_FAILURE = "INITIALIZATION_FAILURE";
