/**
 * Search action types
 */
export const UPDATE_SELECTION = "UPDATE_SELECTION";
export const UPDATE_QUERY = "UPDATE_QUERY";
export const DO_SEARCH = "DO_SEARCH";
export const CLEAR_SELECTION = "CLEAR_SELECTION";
export const CLEAR_QUERY = "CLEAR_QUERY";
export const SEARCH_RESULTS_RECEIVED = "SEARCH_RESULTS_RECEIVED";
export const PAGINATE_SEARCH_RESULTS = "PAGINATE_SEARCH_RESULTS";
